### ISSUE TITLE
Tests failing in master

### ISSUE THREAD

**Issue by lewismc** [lewismc/podaacpy#13]
When I pull master branch and test it I get the following
```
lmcgibbn@LMC-032857 /usr/local/podaacpy(master) $ nosetests
..EEEEEEEEEEEEEEE
======================================================================
ERROR: test_extract_granule (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 56, in test_extract_granule
    result = podaac.extract_granule()
AttributeError: 'module' object has no attribute 'extract_granule'

======================================================================
ERROR: test_list_available_extract_granule_datasetIds (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 91, in test_list_available_extract_granule_datasetIds
    result = podaac.list_available_extract_granule_datasetIds()
AttributeError: 'module' object has no attribute 'list_available_extract_granule_datasetIds'

======================================================================
ERROR: test_list_available_extract_granule_datasetShortNames (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 96, in test_list_available_extract_granule_datasetShortNames
    result = podaac.list_available_extract_granule_datasetShortNames()
AttributeError: 'module' object has no attribute 'list_available_extract_granule_datasetShortNames'

======================================================================
ERROR: test_list_available_granule_search_datasetIds (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 61, in test_list_available_granule_search_datasetIds
    result = podaac.list_available_granule_search_datasetIds()
AttributeError: 'module' object has no attribute 'list_available_granule_search_datasetIds'

======================================================================
ERROR: test_list_available_granule_search_datasetShortNames (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 66, in test_list_available_granule_search_datasetShortNames
    result = podaac.list_available_granule_search_datasetShortNames()
AttributeError: 'module' object has no attribute 'list_available_granule_search_datasetShortNames'

======================================================================
ERROR: test_list_available_granule_search_level2_datasetIds (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 71, in test_list_available_granule_search_level2_datasetIds
    result = podaac.list_available_granule_search_level2_datasetIds()
AttributeError: 'module' object has no attribute 'list_available_granule_search_level2_datasetIds'

======================================================================
ERROR: test_list_available_granule_search_level2_datasetShortNames (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 76, in test_list_available_granule_search_level2_datasetShortNames
    result = podaac.list_available_granule_search_level2_datasetShortNames()
AttributeError: 'module' object has no attribute 'list_available_granule_search_level2_datasetShortNames'

======================================================================
ERROR: test_list_available_image_granule_datasetIds (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 81, in test_list_available_image_granule_datasetIds
    result = podaac.list_available_image_granule_datasetIds()
AttributeError: 'module' object has no attribute 'list_available_image_granule_datasetIds'

======================================================================
ERROR: test_list_available_image_granule_datasetShortNames (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 86, in test_list_available_image_granule_datasetShortNames
    result = podaac.list_available_image_granule_datasetShortNames()
AttributeError: 'module' object has no attribute 'list_available_image_granule_datasetShortNames'

======================================================================
ERROR: test_load_dataset_md (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 26, in test_load_dataset_md
    result = podaac.load_dataset_md()
AttributeError: 'module' object has no attribute 'load_dataset_md'

======================================================================
ERROR: test_load_granule_md (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 31, in test_load_granule_md
    result = podaac.load_granule_md()
AttributeError: 'module' object has no attribute 'load_granule_md'

======================================================================
ERROR: test_load_image_granule (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 51, in test_load_image_granule
    result = podaac.load_image_granule()
AttributeError: 'module' object has no attribute 'load_image_granule'

======================================================================
ERROR: test_load_last24hours_datacasting_granule_md (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 36, in test_load_last24hours_datacasting_granule_md
    result = podaac.load_last24hours_datacasting_granule_md()
AttributeError: 'module' object has no attribute 'load_last24hours_datacasting_granule_md'

======================================================================
ERROR: test_search_dataset (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 41, in test_search_dataset
    result = podaac.search_dataset()
AttributeError: 'module' object has no attribute 'search_dataset'

======================================================================
ERROR: test_search_granule (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 46, in test_search_granule
    result = podaac.search_granule()
AttributeError: 'module' object has no attribute 'search_granule'

----------------------------------------------------------------------
Ran 17 tests in 8.326s

FAILED (errors=15)
lmcgibbn@LMC-032857 /usr/local/podaacpy(master) $
```

**Comment by lewismc** [comment]
@Omkar20895

**Comment by Omkar20895** [comment]
That pull request was outdated and had unstable tests. I have opened a new pull request [PR#18](https://github.com/lewismc/podaacpy/pull/18), It has also passed the travis-ci build. Thanks. :)

**Comment by lewismc** [comment]
Thanks @Omkar20895
