### ISSUE TITLE
Tests failing in master

### ISSUE THREAD

**Issue by lewismc** [lewismc/podaacpy#21]
Hi @Omkar20895 the following tests are failing. Can you take a look. This is running off of a clean master branch.
```
lmcgibbn@LMC-032857 /usr/local/podaacpy(master) $ nosetests
.......EE......EEEEEEEEEEEEEEE
======================================================================
ERROR: podaac.nose_tests_podaac.podaac_test.test_list_available_granule_search_datasetIds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/podaacpy/podaac/nose_tests_podaac/podaac_test.py", line 81, in test_list_available_granule_search_datasetIds
    data = podaac.list_available_granule_search_datasetIds()
  File "/usr/local/podaacpy/podaac/podaac.py", line 458, in list_available_granule_search_datasetIds
    json = requests.get("http://podaac.jpl.nasa.gov/dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json").json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): podaac.jpl.nasa.gov
requests.packages.urllib3.connectionpool: DEBUG: "GET /dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json HTTP/1.1" 503 323
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: podaac.nose_tests_podaac.podaac_test.test_list_available_granule_search_datasetShortNames
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/podaacpy/podaac/nose_tests_podaac/podaac_test.py", line 89, in test_list_available_granule_search_datasetShortNames
    data = podaac.list_available_granule_search_datasetShortNames()
  File "/usr/local/podaacpy/podaac/podaac.py", line 488, in list_available_granule_search_datasetShortNames
    json = requests.get("http://podaac.jpl.nasa.gov/dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json").json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): podaac.jpl.nasa.gov
requests.packages.urllib3.connectionpool: DEBUG: "GET /dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json HTTP/1.1" 503 323
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_extract_granule (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 56, in test_extract_granule
    result = podaac.extract_granule()
AttributeError: 'module' object has no attribute 'extract_granule'

======================================================================
ERROR: test_list_available_extract_granule_datasetIds (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 91, in test_list_available_extract_granule_datasetIds
    result = podaac.list_available_extract_granule_datasetIds()
AttributeError: 'module' object has no attribute 'list_available_extract_granule_datasetIds'

======================================================================
ERROR: test_list_available_extract_granule_datasetShortNames (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 96, in test_list_available_extract_granule_datasetShortNames
    result = podaac.list_available_extract_granule_datasetShortNames()
AttributeError: 'module' object has no attribute 'list_available_extract_granule_datasetShortNames'

======================================================================
ERROR: test_list_available_granule_search_datasetIds (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 61, in test_list_available_granule_search_datasetIds
    result = podaac.list_available_granule_search_datasetIds()
AttributeError: 'module' object has no attribute 'list_available_granule_search_datasetIds'

======================================================================
ERROR: test_list_available_granule_search_datasetShortNames (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 66, in test_list_available_granule_search_datasetShortNames
    result = podaac.list_available_granule_search_datasetShortNames()
AttributeError: 'module' object has no attribute 'list_available_granule_search_datasetShortNames'

======================================================================
ERROR: test_list_available_granule_search_level2_datasetIds (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 71, in test_list_available_granule_search_level2_datasetIds
    result = podaac.list_available_granule_search_level2_datasetIds()
AttributeError: 'module' object has no attribute 'list_available_granule_search_level2_datasetIds'

======================================================================
ERROR: test_list_available_granule_search_level2_datasetShortNames (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 76, in test_list_available_granule_search_level2_datasetShortNames
    result = podaac.list_available_granule_search_level2_datasetShortNames()
AttributeError: 'module' object has no attribute 'list_available_granule_search_level2_datasetShortNames'

======================================================================
ERROR: test_list_available_image_granule_datasetIds (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 81, in test_list_available_image_granule_datasetIds
    result = podaac.list_available_image_granule_datasetIds()
AttributeError: 'module' object has no attribute 'list_available_image_granule_datasetIds'

======================================================================
ERROR: test_list_available_image_granule_datasetShortNames (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 86, in test_list_available_image_granule_datasetShortNames
    result = podaac.list_available_image_granule_datasetShortNames()
AttributeError: 'module' object has no attribute 'list_available_image_granule_datasetShortNames'

======================================================================
ERROR: test_load_dataset_md (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 26, in test_load_dataset_md
    result = podaac.load_dataset_md()
AttributeError: 'module' object has no attribute 'load_dataset_md'

======================================================================
ERROR: test_load_granule_md (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 31, in test_load_granule_md
    result = podaac.load_granule_md()
AttributeError: 'module' object has no attribute 'load_granule_md'

======================================================================
ERROR: test_load_image_granule (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 51, in test_load_image_granule
    result = podaac.load_image_granule()
AttributeError: 'module' object has no attribute 'load_image_granule'

======================================================================
ERROR: test_load_last24hours_datacasting_granule_md (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 36, in test_load_last24hours_datacasting_granule_md
    result = podaac.load_last24hours_datacasting_granule_md()
AttributeError: 'module' object has no attribute 'load_last24hours_datacasting_granule_md'

======================================================================
ERROR: test_search_dataset (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 41, in test_search_dataset
    result = podaac.search_dataset()
AttributeError: 'module' object has no attribute 'search_dataset'

======================================================================
ERROR: test_search_granule (podaac.tests.test_podaac.TestPodaacDataWebservices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/podaacpy/podaac/tests/test_podaac.py", line 46, in test_search_granule
    result = podaac.search_granule()
AttributeError: 'module' object has no attribute 'search_granule'

----------------------------------------------------------------------
Ran 30 tests in 19.359s

FAILED (errors=17)
```

**Comment by Omkar20895** [comment]
@lewismc there are only 15 test cases in the master branch right now, How come you have 30 test case in your master?? I think the rest 15 are the outdated previous tests that I have sent. 
Please take a look at this link https://travis-ci.org/lewismc/podaacpy/builds/136642257 for reference.
13/15 test cases pass and the rest two fail because of the reason I have mentioned to you earlier. Hope this helps. Thanks :)

**Comment by Omkar20895** [comment]
@lewismc from what I have understood, the first 15 test cases you have run are the test cases from the master branch and the rest of the 15 test cases are outdated I guess. Thanks.

**Comment by lewismc** [comment]
I am installing podaacpy as following

Git clone $master

Python setup.py install

Nosetests

I then have the failing tests

On Friday, June 10, 2016, Omkar <notifications@github.com> wrote:

> @lewismc <https://github.com/lewismc> from what I have understood, the
> first 15 test cases you have run are the test cases from the master branch
> and the rest of the 15 test cases are outdated I guess. Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lewismc/podaacpy/issues/21#issuecomment-225340137>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABHJl6FOVmVdJtac-Gn_GUoEwcyLS4naks5qKlXCgaJpZM4Izdu7>
> .
>


-- 
*Lewis*

**Comment by Omkar20895** [comment]
@lewismc I have used the same instructions that you have used in the same order.. I have got only 15 tests running in my system.
>> git clone $master
>>python setup.py install 

![screen shot 2016-06-12 at 2 43 41 pm](https://cloud.githubusercontent.com/assets/11131863/15990282/38f5f2d8-30ac-11e6-9249-7d44366cb910.png)

>>nosetests 
![screen shot 2016-06-12 at 2 45 25 pm](https://cloud.githubusercontent.com/assets/11131863/15990288/58a23c2c-30ac-11e6-8753-bddc2384be99.png)
![screen shot 2016-06-12 at 2 45 42 pm](https://cloud.githubusercontent.com/assets/11131863/15990289/5b683d8a-30ac-11e6-8c62-7247cea0338c.png)

I can't understand where we are going wrong. Can you please check your package once again?? 
Thanks. :)

**Comment by lewismc** [comment]
OK I solved it. It was my local copy and the cache of it.
Once I deleted it all and work cleanly off of master branch, everything is good. See log output below.
I have an issue however. Please see bottom of this message
```
lmcgibbn@LMC-032857 /usr/local/podaacpy(master) $ nosetests
.......EE......
======================================================================
ERROR: podaac.nose_tests_podaac.podaac_test.test_list_available_granule_search_datasetIds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/podaacpy/podaac/nose_tests_podaac/podaac_test.py", line 81, in test_list_available_granule_search_datasetIds
    data = podaac.list_available_granule_search_datasetIds()
  File "/usr/local/podaacpy/podaac/podaac.py", line 458, in list_available_granule_search_datasetIds
    json = requests.get("http://podaac.jpl.nasa.gov/dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json").json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): podaac.jpl.nasa.gov
requests.packages.urllib3.connectionpool: DEBUG: "GET /dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json HTTP/1.1" 503 323
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: podaac.nose_tests_podaac.podaac_test.test_list_available_granule_search_datasetShortNames
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/podaacpy/podaac/nose_tests_podaac/podaac_test.py", line 89, in test_list_available_granule_search_datasetShortNames
    data = podaac.list_available_granule_search_datasetShortNames()
  File "/usr/local/podaacpy/podaac/podaac.py", line 488, in list_available_granule_search_datasetShortNames
    json = requests.get("http://podaac.jpl.nasa.gov/dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json").json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): podaac.jpl.nasa.gov
requests.packages.urllib3.connectionpool: DEBUG: "GET /dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json HTTP/1.1" 503 323
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 15 tests in 21.104s

FAILED (errors=2)
```
Once tests have been run, I get the following
```
lmcgibbn@LMC-032857 /usr/local/podaacpy(master) $ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	PODAAC-ASOP2-25X01_image.jpg
	doc.txt
	podaac/ascat_20130719_230600_metopa_35024_eps_o_250_2200_ovw.l2.nc

nothing added to commit but untracked files present (use "git add" to track)
lmcgibbn@LMC-032857 /usr/local/podaacpy(master) $
```
The offending files should be cleaned up after the tests are complete. This is important.

**Comment by Omkar20895** [comment]
Okay sure I will do that. Thanks. :)

**Comment by Omkar20895** [comment]
Okay sure I am on it! Thanks.

**Comment by Omkar20895** [comment]
We don't need to delete the doc.txt file right?? pardon me if this question is silly. Thanks
